management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics

app:
  processing:
    concurrency: 50

spring:
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://db:3306/test_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: users-datasource
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 60000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect